/**
 * @author ferreiraluizga
 */
package cadastroDeCliente;

//imports
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

public class CadastrarDev extends javax.swing.JInternalFrame {
    /**
     * Creates new form CadastrarDev
     */
    public CadastrarDev() {
        initComponents(); 
        setDataAtual();

        //dicas nos botões
        btnIncluir.setToolTipText("Cadastrar cliente no sistema");
        btnLimpar.setToolTipText("Limpar dados escritos");
        btnSair.setToolTipText("Sair do sistema");
    }
    
    private void setDataAtual() {
        // data local do dispositivo
        LocalDate dataAtual = LocalDate.now();

        // formatar data no formato dd/MM/yyyy
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String dataFormatada = dataAtual.format(formatter);

        // colocando a data local e formatada no campo que indica a data de cadastro
        txtDataCadastro.setText(dataFormatada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGenero = new javax.swing.ButtonGroup();
        btnGroupCivil = new javax.swing.ButtonGroup();
        rdnSolteiro = new javax.swing.JRadioButton();
        rdnCasado = new javax.swing.JRadioButton();
        lblTitulo = new javax.swing.JLabel();
        lblDataCadastro = new javax.swing.JLabel();
        lblCivil = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblVagas = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        checkFront = new javax.swing.JCheckBox();
        txtBairro = new javax.swing.JTextField();
        checkBack = new javax.swing.JCheckBox();
        txtCidade = new javax.swing.JTextField();
        checkFull = new javax.swing.JCheckBox();
        txtCelular = new javax.swing.JFormattedTextField();
        checkDados = new javax.swing.JCheckBox();
        txtTelefone = new javax.swing.JFormattedTextField();
        comboBoxEstado = new javax.swing.JComboBox<>();
        checkAnalista = new javax.swing.JCheckBox();
        checkCloud = new javax.swing.JCheckBox();
        txtCep = new javax.swing.JFormattedTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        lblId = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        lblEndereco = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblBairro = new javax.swing.JLabel();
        rdnIndefinido = new javax.swing.JRadioButton();
        lblCidade = new javax.swing.JLabel();
        rdnMasculino = new javax.swing.JRadioButton();
        lblEstado = new javax.swing.JLabel();
        rdnFeminino = new javax.swing.JRadioButton();
        lblCep = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        rdnViuvo = new javax.swing.JRadioButton();
        lblTelefone = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastrar Desenvolvedor");

        btnGroupCivil.add(rdnSolteiro);
        rdnSolteiro.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rdnSolteiro.setText("Solteiro(a)");

        btnGroupCivil.add(rdnCasado);
        rdnCasado.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rdnCasado.setText("Casado(a)");

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro de Desenvolvedor");

        lblDataCadastro.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblDataCadastro.setText("Data de Cadastro:");

        lblCivil.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblCivil.setText("Estado Civil:");

        txtDataCadastro.setEnabled(false);

        lblComplemento.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblComplemento.setText("Complemento:");

        txtId.setText("1");
        txtId.setEnabled(false);

        lblVagas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblVagas.setText("Áreas de Interesse e Atuação:");

        checkFront.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkFront.setText("Desenvolvedor Front-End");

        checkBack.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkBack.setText("Desenvolvedor Back-End");

        checkFull.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkFull.setText("Desenvolvedor Full-Stack");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        checkDados.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkDados.setText("Engenheiro de Dados");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        comboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Estado:", "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));

        checkAnalista.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkAnalista.setText("Analista de Sistemas");

        checkCloud.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkCloud.setText("Engenheiro de Cloud");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblId.setText("Código do Desenvolvedor:");

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastroDeCliente/img/addIcon.gif"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNome.setText("Nome Completo:");

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastroDeCliente/img/clearIcon.gif"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblEndereco.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço:");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastroDeCliente/img/closeIcon.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblBairro.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblBairro.setText("Bairro:");

        btnGroupGenero.add(rdnIndefinido);
        rdnIndefinido.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rdnIndefinido.setText("Prefiro não dizer");

        lblCidade.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblCidade.setText("Cidade:");

        btnGroupGenero.add(rdnMasculino);
        rdnMasculino.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rdnMasculino.setText("Masculino");

        lblEstado.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblEstado.setText("Estado:");

        btnGroupGenero.add(rdnFeminino);
        rdnFeminino.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rdnFeminino.setText("Feminino");

        lblCep.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblCep.setText("CEP:");

        lblGenero.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblGenero.setText("Gênero:");

        lblCelular.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblCelular.setText("Celular:");

        btnGroupCivil.add(rdnViuvo);
        rdnViuvo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rdnViuvo.setText("Viúvo(a)");

        lblTelefone.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblDataNascimento.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblDataNascimento.setText("Data de Nascimento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdnIndefinido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdnFeminino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdnMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rdnCasado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdnSolteiro))
                            .addComponent(rdnViuvo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(checkFront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkFull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkCloud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkAnalista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblVagas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCelular)
                                    .addComponent(lblEstado))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(comboBoxEstado, 0, 189, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCelular)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCidade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataCadastro))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblBairro)
                        .addGap(12, 12, 12)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtComplemento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEndereco)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNascimento)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdnMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdnFeminino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdnIndefinido))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCivil)
                            .addComponent(lblVagas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdnSolteiro)
                            .addComponent(checkFront)
                            .addComponent(checkDados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdnCasado)
                            .addComponent(checkBack)
                            .addComponent(checkAnalista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdnViuvo)
                            .addComponent(checkFull)
                            .addComponent(checkCloud))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataCadastro)
                    .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnSair))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        //variaveis para armazenar dados do usuário
        String id, nome, endereco, bairro, complemento, cidade, estado, cep, celular, telefone, dataNascimento, dataCadastro, genero = "", civil = "", areas = "", dadosUsuario;

        //atribuindo informações padrão (id e data local para cadastro)
        id = txtId.getText();
        dataCadastro = txtDataCadastro.getText();

        //verificar se há um nome para registrar um usuário, se não houver, um alerta é emitido
        if (txtNome.getText().equals("")) {
            dadosUsuario = "Para cadastrar um usuário, é necessário pelo menos seu nome."
            + "\nDigite um nome para proseguir.";
            JOptionPane.showMessageDialog(rootPane, dadosUsuario, "Dados do Usuário", JOptionPane.WARNING_MESSAGE);
        } else {
            //verificar se o campo está vazio, ou com dados inseridos pelo usuário
            //obs: se o campo é vazio, na apresentação de resultados ele aparece como "não inserido"

            //nome
            if (txtNome.getText().equals("")) {
                nome = "Não inserido";
            } else {
                nome = txtNome.getText();
            }

            //data de nascimento
            if (txtDataNascimento.getText().equals("  /  /    ")) {
                dataNascimento = "Não inserido";
            } else {
                dataNascimento = txtDataNascimento.getText();
            }

            //genero
            if (rdnMasculino.isSelected() == false && rdnFeminino.isSelected() == false && rdnIndefinido.isSelected() == false) {
                genero = "Não inserido";
            } else if (rdnMasculino.isSelected()) {
                genero = "Masculino";
            } else if (rdnFeminino.isSelected()) {
                genero = "Feminino";
            } else if (rdnIndefinido.isSelected()) {
                genero = "Não Especificado";
            }

            //estado civil
            if (rdnSolteiro.isSelected() == false && rdnCasado.isSelected() == false && rdnViuvo.isSelected() == false) {
                civil = "Não inserido";
            } else if (rdnSolteiro.isSelected()) {
                civil = "Solteiro(a)";
            } else if (rdnCasado.isSelected()) {
                civil = "Casado(a)";
            } else if (rdnViuvo.isSelected()) {
                civil = "Viúvo(a)";
            }

            //areas de atuação
            String temp = "";
            if (checkFront.isSelected()) {
                temp += checkFront.getText() + ", ";
            }
            if (checkBack.isSelected()) {
                temp += checkBack.getText() + ", ";
            }
            if (checkFull.isSelected()) {
                temp += checkFull.getText() + ", ";
            }
            if (checkDados.isSelected()) {
                temp += checkDados.getText() + ", ";
            }
            if (checkAnalista.isSelected()) {
                temp += checkAnalista.getText() + ", ";
            }
            if (checkCloud.isSelected()) {
                temp += checkCloud.getText() + ", ";
            }
            if (temp.equals("")) {
                areas = "Nenhuma área selecionada";
            } else {
                areas = temp.substring(0, temp.length() - 2);
            }

            //cep
            if (txtCep.getText().equals("     -   ")) {
                cep = "Não inserido";
            } else {
                cep = txtCep.getText();
            }

            //endereco
            if (txtEndereco.getText().equals("")) {
                endereco = "Não inserido";
            } else {
                endereco = txtEndereco.getText();
            }

            //bairro
            if (txtBairro.getText().equals("")) {
                bairro = "Não inserido";
            } else {
                bairro = txtBairro.getText();
            }

            //complemento
            if (txtComplemento.getText().equals("")) {
                complemento = "Não inserido";
            } else {
                complemento = txtComplemento.getText();
            }

            //estado
            if (comboBoxEstado.getSelectedIndex() == 0) {
                estado = "Não inserido";
            } else {
                estado = String.valueOf(comboBoxEstado.getSelectedItem());
            }

            //cidade
            if (txtCidade.getText().equals("")) {
                cidade = "Não inserido";
            } else {
                cidade = txtCidade.getText();
            }

            //celular
            if (txtCelular.getText().equals("(  )      -    ")) {
                celular = "Não inserido";
            } else {
                celular = txtCelular.getText();
            }

            //telefone
            if (txtTelefone.getText().equals("(  )     -    ")) {
                telefone = "Não inserido";
            } else {
                telefone = txtTelefone.getText();
            }

            //apresentando informações digitadas pelo usuário
            dadosUsuario = "Número de Cadastro: " + id
            + "\nNome Completo: " + nome
            + "\nData de Nascimento: " + dataNascimento
            + "\nGênero: " + genero
            + "\nEstado Civil: " + civil
            + "\nÁreas de Interesse e Atuação: " + areas
            + "\nCEP: " + cep
            + "\nEndereço: " + endereco
            + "\nBairro: " + bairro
            + "\nComplemento: " + complemento
            + "\nEstado: " + estado
            + "\nCidade: " + cidade
            + "\nCelular: " + celular
            + "\nTelefone: " + telefone
            + "\nData de Cadastro: " + dataCadastro;

            JOptionPane.showMessageDialog(rootPane, dadosUsuario, "Dados do Usuário", JOptionPane.INFORMATION_MESSAGE);

            //atualizar número de cadastro para próximo cliente
            int numCadastro = Integer.parseInt(txtId.getText()) + 1;
            txtId.setText(String.valueOf(numCadastro));

            //limpando campos para próximo cadastro
            txtNome.setText(null);
            txtDataNascimento.setText(null);
            btnGroupGenero.clearSelection();
            btnGroupCivil.clearSelection();
            checkFront.setSelected(false);
            checkBack.setSelected(false);
            checkFull.setSelected(false);
            checkDados.setSelected(false);
            checkAnalista.setSelected(false);
            checkCloud.setSelected(false);
            txtCep.setText(null);
            txtEndereco.setText(null);
            txtBairro.setText(null);
            txtComplemento.setText(null);
            comboBoxEstado.setSelectedIndex(0);
            txtCidade.setText(null);
            txtCelular.setText(null);
            txtTelefone.setText(null);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        //limpar campos de cadastro e colocando foco na primeira caixa de texto
        txtNome.setText(null);
        txtDataNascimento.setText(null);
        btnGroupGenero.clearSelection();
        btnGroupCivil.clearSelection();
        checkFront.setSelected(false);
        checkBack.setSelected(false);
        checkFull.setSelected(false);
        checkDados.setSelected(false);
        checkAnalista.setSelected(false);
        checkCloud.setSelected(false);
        txtCep.setText(null);
        txtEndereco.setText(null);
        txtBairro.setText(null);
        txtComplemento.setText(null);
        comboBoxEstado.setSelectedIndex(0);
        txtCidade.setText(null);
        txtCelular.setText(null);
        txtTelefone.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupCivil;
    private javax.swing.ButtonGroup btnGroupGenero;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JCheckBox checkAnalista;
    private javax.swing.JCheckBox checkBack;
    private javax.swing.JCheckBox checkCloud;
    private javax.swing.JCheckBox checkDados;
    private javax.swing.JCheckBox checkFront;
    private javax.swing.JCheckBox checkFull;
    private javax.swing.JComboBox<String> comboBoxEstado;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCivil;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDataCadastro;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVagas;
    private javax.swing.JRadioButton rdnCasado;
    private javax.swing.JRadioButton rdnFeminino;
    private javax.swing.JRadioButton rdnIndefinido;
    private javax.swing.JRadioButton rdnMasculino;
    private javax.swing.JRadioButton rdnSolteiro;
    private javax.swing.JRadioButton rdnViuvo;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
